### ISSUE TITLE
Global Pin

### ISSUE THREAD

**Issue by seeker20** [Lan2Play/eventula_entrance_client#44]
Der Userpin lautet: 1234
Admin Pin lautet: 4637

Falls man die mal vergessen haben sollte, oder jemand die orginal software codes kompiliert hat

**Comment by Apfelwurm** [comment]
Die Admin Pin ist bereits in der README enthalten und die userpin sollte so oder so neu vergeben werden. Da das hier ein Hinweis und kein issue ist, schließe ich :)
